apiVersion: apps/v1
kind: Deployment
metadata:
  name: new0804a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: new0804a
  template:
    metadata:
      labels:
        app: new0804a
    spec:
      containers:
      - image: okteto.dev/new0804a:latest
        name: new0804a
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "ffbdb2e3-1ca8-4d40-9be2-aff2b400594f"
        - name: Vless_Path
          value: "/vlrtrt4"
        - name: Vmess_UUID
          value: "ffbdb2e3-1ca8-4d40-9be2-aff2b400594f"
        - name: Vmess_Path
          value: "/vm546gr"
        - name: Share_Path
          value: "/v2link"
